### ISSUE TITLE
[프로젝트 설정] Assets관리 선언형 라이브러리 활용

### ISSUE THREAD

**Issue by sseungmn** [boostcampwm-2022/iOS09-eoljug-a#42]
## 할 일

- [x] R.Swift, SwiftGen 비교 분석
- [x] 팀원들의 동의 얻기
- [x] 프로젝트에 적용

**Comment by sseungmn** [comment]
# R.swift

### 장점

1. **완전한 형식화 → 캐스팅을 줄이고 명확한 리턴 타입**
2. **컴파일때 코드 생성 및 유효성 검사 → 런타임 시 앱 크래쉬 방지**
3. **자동 완성 → 파일명을 직접 타이핑 할 필요 없어, 오탈자 방지**
4. 폴더를 검사하는 것이 아닌, Xcodeproj를 검사한다. → 이게 왜 장점?
5. 다양한 assets에 대한 지원
6. vanilla Apple API와 매우 밀접해, 작은 코드 변화로 큰 임펙트를 낼 수 있다.

### 단점

1. 라이브러리를 설치해야 할 듯 하다.
2. 특정 리소스에만 적용이 불가능하고, 모든 리소스에 적용된다.

### 동작 방식

1. 빌드를 할 때마다 R.swift가 실행된다.
2. xcodeproj 파일을 검사해서 타겟과 현재 연결된 모든 리소스를 빌드한다.
3. `R.generated.swift`파일을 생성해서 모든 리소스를 구조화한다.

# SwiftGen

### 장점

1. 라이브러리를 설치할 필요 없이, Homebrew로 로컬에서 돌릴 수 있다. like SwiftLint
2. 적용 하고 싶은 리소스를 지정할 수 있다.

**Comment by sseungmn** [comment]
관련 포스트 : [Asset 선언적으로 관리하기](https://sseungmn.notion.site/Asset-8979d3dfc285472ca584efb904d9d8bb)

**Comment by NEULiee** [comment]
폴더를 검사하면 일일히 다 탐색해야하는데 Xcodeproj를 검사하면 파일 하나만 검사하기 때문에 시간적으로 성능이 더 좋지 않을까 싶네요!?
