### ISSUE TITLE
[앱 초기 설정] 설정화면 - Coordinator 설정

### ISSUE THREAD

**Issue by NEULiee** [boostcampwm-2022/iOS09-eoljug-a#6]
## 할 일

- [x]  Cooordinator 패턴 설정
- [x]  TabBar 설정
- [x]  메인 스토리보드 제거

**Comment by never-better** [comment]
출처 : https://somevitalyz123.medium.com/coordinator-pattern-with-tab-bar-controller-33e08d39d7d
